name: visualize
on: 
    push:
        branches:
            - main
jobs:
    visualize:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Repo Visualizer
              uses: githubocto/repo-visualizer@0.9.1
              with:
                branch: main
                # If given, the name of an artifact to be created containing the diagram. Default: don't create an artifact.
                artifact_name: diagram 
          
